layers/meta-balena-imx8m-var-dart/recipes-core/images/resin-image-initramfs.bbappend
Merge when bumped to 2.47
Since 2.47.0, IMAGE_ROOTFS_MAXSIZE is now 32M
in meta-balena-common
See https://github.com/balena-os/meta-balena/pull/1813 for more detail.
Changelog-entry: Cleanup unnecessary use of IMAGE_ROOTFS_MAXSIZE 
Signed-off-by: Zubair Lutfullah Kakakhel <zubair@balena.io>
=> resin-image-initramfs: Remove IMAGE_ROOTFS_MAXSIZE

imx8mm-var-dart-plt.coffee
This step is no longer necessary as now board
is flashed only if the boot switch is the EXT position.
Changelog-entry: imx8mm-var-dart-plt: Remove unnecessary step from coffee file
=> imx8mm-var-dart-plt: Remove unnecessary step from coffee file

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/mx8mm-nrt-Enable-M4-run-from-DDR.patch, layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/u-boot-variscite.bbappend
Now that rpmsg is requested as necessary, switch to M4 dtb and also switch m4 bin load address to DDR.
=> Switch to M4 dtb, update BalenaOS

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/mx8mm-nrt-Enable-M4-run-from-TCM.patch, layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/u-boot-variscite.bbappend
This reverts commit 71d0b920e53d06e39a32361111d5689357cd83c3.
Customer realised that they won't be able to use spi when using the m4
dtb even though we were clear about this.
Changelog-entry: Revert "u-boot: Switch to DDR for the M4 load address" so that customer can use spi
=> u-boot: Revert "u-boot: Switch to DDR for the M4 load address"

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite/0007-arm64-dts-fsl-imx8mm-var-dart-Disable-CQE-for-the-eM.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
We have observed CQE presents some stability issues on
imx8mm-var-dart-nrt so let's disable CQE for this board.
Changelog-entry: Disable CQE for imx8mm-var-dart-nrt
=> linux-variscite: Disable CQE for imx8mm-var-dart-nrt

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite/0008-dts-fsl-imx8mm-var-dart-Disable-GPU.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
This was requested by customer
Changelog-entry: Disable GPU for imx8mm-var-dart-nrt as requested by customer
=> linux-variscite: Disable GPU for imx8mm-var-dart-nrt

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/imx8mm-var-dart-Enable-I2C.patch, layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/u-boot-variscite.bbappend
Tested with reading DS1307 rtc time on the DT8M Customboard v1.4
```
i2c bus
Bus 0:  i2c@30a20000  (active 0)
52: generic_52, offset len 1, flags 0
Bus 1:  i2c@30a30000
Bus 2:  i2c@30a40000
u-boot=> i2c dev 1
Setting bus to 1
u-boot=> i2c probe
Valid chip addresses: 3D 54 55 68
u-boot=> i2c md 0x68 0 3
0000: 01 03 00    ...
```
=> Enable I2C commands in uboot for iMX8MM PLT

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/dart-mx8mm-Integrate-with-Balena-u-boot-environment.patch
This was added as extra but it causes boot hang for the nrt board on which
we disabled the gpu. So let's just disable it and follow the original
mmcargs settings.
Changelog-entry: Remove video kernel cmdline param for imx8mm-var-dart based boards
=> u-boot: Do not add video kernel cmdline param for imx8mm-var-dart

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/u-boot-variscite.bbappend
Using this kernel cmdline param the board will freeze at booting when
initializing the drm.
Changelog-entry: Remove console=null kernel cmdline param for imx8mm-var-dart-nrt
=> u-boot-variscite: Remove console=null from prod imx8mm-var-dart-nrt

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
These were removed as necessay for the laird
module. Now that's not being used anymore,
we need to add them back for on-board
wifi an bt.
Changelog-entry: linux-variscite: Remove laird configs
=> linux-variscite: Remove laird configs

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite/0001-disable-gigabit.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
We disable gigabit and let it fallback to 100Mbps because currently on
gigabit the link would go down at random times and networking is dead.
Changelog-entry: Disable gigabit for imx8mm-var-dart-plt
=> linux-variscite: Disable gigabit for imx8mm-var-dart-plt

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
Disable commit SHA in version string to avoid
version magic mismatch for modules.
Addresses: https://github.com/balena-os/balena-variscite-mx8/issues/15
=> linux-variscite: Disable commit SHA in version string

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite/imx8mm-var-dart-plt-Disable-PCIe.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
The hw vendor suggests we disable PCIe to have the new
imx8mm-var-dart-plt revision boot correctly.
Changelog-entry: Disable PCIe for the new imx8mm-var-dart-plt revision to boot correctly
=> linux-variscite: Disable PCIe for imx8mm-var-dart-plt

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
Touchscreen won't be used on the imx8mm-var-dart-plt board so let's
disable it so that we also free up gpio-3.
Changelog-entry: Disable ADS7846 touchscreen controller for imx8mm-var-dart-plt
=> linux-variscite_%.bbappend: Disable ADS7846 for imx8mm-var-dart-plt

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite/0010-fsl-imx8mm-var-dart-Update-pinmux-for-NRT-board.patch
User wants to use GPIO5_IO01, let's remove the wm8904 node
which modified this.
Changelog-entry: linux-variscite: Updates for new NRT hw pinmuxes
=> linux-variscite: Updates for new NRT board pinmuxes

.gitmodules
versionbot does not support ssh
Changelog-entry: update git submodules to use https
Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>
=> gitmodules: Update to use https instead of ssh

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite/0011-imx8mm-var-dart-nrt-Add-LP55231-to-the-device-tree.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
Connects to: https://github.com/balena-os/balena-variscite-mx8/issues/83
Changelog-entry: imx8mm-var-dart-nrt: Add LP55231 driver and dt entry
Signed-off-by: Alexanru Costache <alexandru@balena.io>
=> imx8mm-var-dart-nrt: Add LP55231 driver and dt entry

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/imx8mm-var-dart-nrt-Add-led-start-routine-for-NRT.patch
The values for the registers and sequence
are provided by the user of the NRT board.
Changelog-entry: u-boot: Add i2c commands for led current
=> u-boot: Add i2c commands for led current on NRT

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/imx8mm-var-dart-nrt-Add-led-start-routine-for-NRT.patch
User asked to switch the sequence for the leds
to set the current first.
Changelog-entry: u-boot-variscite: Set led current first
=> u-boot-variscite: Set led current first

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite-5.4.85/0001-lp55xx-Add-support-for-default-startup-brightness-fr.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite-5.4.85/imx8mm-var-dart-nrt-Add-LP55231-to-the-device-tree.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
According to: https://jel.ly.fish/support-thread-1-0-0-front-cnv-ceqsqz1
=> NRT: Add support for default LP55231 brightness configuration at startup

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/Use-old-device-tree-on-altboot.patch
We need to use the corresponding imx-boot binary during
rollback-altboot if the kernel and device-tree are
older than the current 5.4.24 imx-boot, otherwise the old kernel will
hang when booted with a newer imx-boot.
We thus write the old version of imx-boot during rollback-altboot
if the device-tree name in the old rootfs does not correspond to
the latest upstream naming scheme.
Changelog-entry: u-boot: Use old imx-boot on imx8mm-var-dart-plt during rollback
=> u-boot: Use old imx-boot on imx8mm-var-dart-plt during rollback

layers/meta-balena-imx8m-var-dart/conf/samples/bblayers.conf.sample
Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
Signed-off-by: Alex Gonzalez <alexg@balena.io>
=> bblayers: Modify layer ordering

layers/meta-balena-imx8m-var-dart/conf/layer.conf
... to save some space
Changelog-entry: conf/layer: Enable firmware compression for imx8m-var-dart
=> conf/layer: Enable firmware compression for imx8m-var-dart

layers/meta-balena-imx8m-var-dart/conf/machine/imx8m-var-dart.conf, layers/meta-balena-imx8m-var-dart/conf/machine/imx8mm-var-dart-nrt.conf, layers/meta-balena-imx8m-var-dart/conf/machine/imx8mm-var-dart-plt.conf, layers/meta-balena-imx8m-var-dart/conf/machine/imx8mm-var-dart.inc, layers/meta-balena-imx8m-var-dart/conf/machine/imx8mm-var-som.conf, layers/meta-balena-imx8m-var-dart/conf/machine/imx8mq-var-dart.inc
balenaOS needs this variable to reflect the real size of the root filesysem.
Changelog-entry: do not set ROOTFS_SIZE in machine configuration
Signed-off-by: Alex Gonzalez <alexg@balena.io>
=> imx8mm-var-dart-nrt: do not set ROOTFS_SIZE

layers/meta-balena-imx8m-var-dart/conf/samples/bblayers.conf.sample
Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf
Signed-off-by: Alex Gonzalez <alexg@balena.io>
=> bblayers.conf.sample: add meta-perl

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite-5.4.142/nrt-add-cw2015-profile-to-imx8mm-var-dart.dtsi.patch, layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
Profile has been provided by customer. See patch
for internal thread link.
Changelog-entry: linux-variscite: Add cw2015 battery profile for NRT
=> linux-variscite: Add cw2015 battery profile for NRT

layers/meta-balena-imx8m-var-dart/recipes-kernel/linux/linux-variscite_%.bbappend
As requested by customer, who will switch to a userspace driver
Changelog-entry: linux-variscite: Remove lp55231 driver for NRT DT
=> linux-variscite: Remove lp55231 driver for NRT DT

layers/meta-balena-imx8m-var-dart/recipes-core/images/balena-image.inc
The extra_uEnv.txt file is installed by meta-balena in the non-flasher image so that it can be manipulated by the supervisor, but there's no other reason for including it in the flasher by the yocto build.
This was a leftover from testing the custom dtbs during provisioning, let's remove it because it causes problems for the nodejs file manipulation library during provisioning of boards which use a button for toggling boot from sd-cards.
Changelog-entry: recipes-core/images: Don't install extra_uEnv.txt in flasher image
=> recipes-core/images: Don't install extra_uEnv.txt in flasher image

layers/meta-balena-imx8m-var-dart/recipes-core/images/balena-image-initramfs.bbappend
On other devices we noticed that the mnt-sysroot-inactive.mount unit cannot activate during first boot after provisioning, unless it is restarted. The automount hangs only during the first boot, upon reboot starts working normally.
We add back the migrate module to avoid potential cases like this.
Changelog-entry: balena-image-initramfs: Add back migrate initramfs module
=> balena-image-initramfs: Add back migrate initramfs module

layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/files/0001-imx8mm-Increase-load-addresses-for-zipped-kernel-and.patch, layers/meta-balena-imx8m-var-dart/recipes-bsp/u-boot/u-boot-variscite.bbappend
To allow for newer Kirkstone-based releases to boot in Autokit with the current imx-boot. The Kirkstone kernel 5.15.60 is larger than kernel 5.4, hence we update the two addresses to avoid the unpacked kernel overlapping with the zipped image during decompression. 
This is a prerequisite to https://github.com/balena-os/balena-variscite-mx8/issues/393
=> Update kernel and fdt addreses

layers/meta-balena-imx8m-var-dart/recipes-connectivity/bluez5/bluez5_%.bbappend, layers/meta-balena-imx8m-var-dart/recipes-connectivity/bluez5/files/0005-scan_len.patch
... to work around autokit sporadic scan reporting no results.
The scan appears to work fine outside autokit on the PLT device and this could be caused by interferences and caching.
Changelog-entry: Increase BT scan length, flush caches on PLT
=> bluez: Increase scan duration and make sure caches are flushed
